let frutas = ['maça', 'banana', 'laranja'];
console.log( frutas.length);
console.log(frutas);
frutas.push('manga');
console.log(frutas);
console.log(frutas.length);
frutas.pop();
frutas.pop();
console.log(frutas);
frutas.pop();
frutas.pop();
console.log(frutas);
frutas.push('uva');
frutas.push('amora');
frutas.push('michirica', 'abacate', 'abacaxi');
console.log(frutas);
console.log('a fruta na posição 1 é:', frutas[1]);
console.log(frutas.length);
console.log('o total de registros é de ', frutas.length+1, 'frutas.');
frutas.unshift('seereja');
console.log(frutas);